---
##Mariadbのレポジトリ登録
- name: install repository key
  yum_repository:
    name: mariadb
    description: Galera Cluster Repo
    baseurl: http://yum.mariadb.org/{{ mariadb_release }}/centos7-amd64/
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-Mariadb
    gpgcheck: yes
    file: MariaDB

  yum:
    name: "{{ item }}"
    state: present
    enablerepo: mariadb
  with_items: "{{ mariadb_packages }}"

##MariaDBのインストール
#  with_items:
#      - MariaDB-Galera-server
#      - Mariadb-Client
#      - galera
#      - rsync
#      - MySQL-python
