---
- name: configure / input hostname
  pause:
    prompt: Please input hostname
  register: input_hostname

- name: configure / hostname settings
    replace: dest=/etc/hostname
      regexp='^ip-.*'
      replace="{{ input_hostname }}"
      backup=yes
...
