---
- name: configure / input hostname
  pause:
    prompt: Please input hostname
  register: input_hostname

- name: configure / hostname settings
  lineinfile:
    path: /etc/hostname
    regexp: '^ip-.*'
    insertafter: ' {{ input_hostname }} '
    line: '^ip-.*'
    backup: yes

    replace: dest=/etc/hostname
      regexp='^ip-.*'
      replace="{{ input_hostname }}"
      backup=yes
...
