---
- name: configure / input hostname
  pause:
    prompt: Please input hostname
  register: input_hostname

- name: configure / hostname settings
  lineinfile:
    path: /home/ec2-user/hostname
#    path: /etc/hostname
    regexp: '^ip-.*'
    line: '{{ input_hostname }}'
#    state: present
    backup: yes
...
