---
## install / for Amazon linux2

## PHP-FPMのインストール
 - name: install /Install required packages
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: remi-php56
  with_items: "{{ php_packages }}"
