---
## install / for Amazon linux2
- name: install / Import repository
  rpm: state=installed file=http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.8-1.el7_4.ngx.x86_64.rpm

## PHP-FPMのインストール
# - name: install /Install required packages
#  yum:
#    name: "{{ item }}"
#    state: present
#    enablerepo: remi-php56
#  with_items: "{{ php_packages }}"
