---
## Wordpressのデプロイ
- name: install / Download Wordpress
  git:
    repo: https://github.com/WordPress/WordPress
    dest: "/home/ec2-user/wordpress-{{ wordpress_version }}"
    version: "{{ wordpress_version }}-branch"

## ドキュメントルートの作成
- name: install / Link wordpress root document
  file:
    src: /home/ec2-user/wordpress-{{ wordpress_version }}
    path: /var/www/html/wordpress
    owner: apache
    group: apache
    state: link

## パーミッションの変更
- name: install / Permission change
  file:
    path: /home/ec2-user/wordpress-{{ wordpress_version }}
    owner: apache
    group: apache
    mode: 755
    recurse: yes

## ドキュメントルートの所有権設定
- name: install / Change ownership in WordPress
  file:
    path: /home/ec2-user/wordpress-{{ wordpress_version }}
    owner: apache
    group: apache
    recurse: yes
...
