---
## Nginxのインストール

- name: install / Install the nginx rpm from a remote repo
  yum:
    name: http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.8-1.el7_4.ngx.x86_64.rpm
    state: present

- name: install / Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_packages }}"
...
